"""
ds_locations.py
---------------
Registry of the specific Divisional Secretariat (DS) divisions in Sri Lanka requested.
"""

DS_LOCATIONS = [
    {"id": "Ududumbara", "district": "Kandy", "province": "Central", "lat": 7.3000, "lon": 80.8333},
    {"id": "Laggala", "district": "Matale", "province": "Central", "lat": 7.6000, "lon": 80.7500},
    {"id": "Lunugala", "district": "Badulla", "province": "Uva", "lat": 7.0000, "lon": 81.0500},
    {"id": "Kothmale East", "district": "Nuwara Eliya", "province": "Central", "lat": 7.1000, "lon": 80.6167},
    {"id": "Passara", "district": "Badulla", "province": "Uva", "lat": 7.0500, "lon": 81.1500},
    {"id": "Meegahakiula", "district": "Badulla", "province": "Uva", "lat": 6.9833, "lon": 81.0000},
    {"id": "Soranathota", "district": "Badulla", "province": "Uva", "lat": 7.1500, "lon": 81.0500},
    {"id": "Rideegama", "district": "Kurunegala", "province": "North Western", "lat": 7.7167, "lon": 80.3833},
    {"id": "Hanguranketa", "district": "Nuwara Eliya", "province": "Central", "lat": 7.1667, "lon": 80.8000},
    {"id": "Kandeketiya", "district": "Badulla", "province": "Uva", "lat": 7.0833, "lon": 81.1833},
    {"id": "Thalawakele", "district": "Nuwara Eliya", "province": "Central", "lat": 6.9360, "lon": 80.6540},
    {"id": "Medadumbara", "district": "Kandy", "province": "Central", "lat": 7.3333, "lon": 80.7833},
    {"id": "Minipe", "district": "Kandy", "province": "Central", "lat": 7.3500, "lon": 80.9167},
    {"id": "Deltota", "district": "Kandy", "province": "Central", "lat": 7.2000, "lon": 80.5333},
    {"id": "Doluwa", "district": "Kandy", "province": "Central", "lat": 7.2167, "lon": 80.7167},
    {"id": "Mathurata", "district": "Nuwara Eliya", "province": "Central", "lat": 7.0833, "lon": 80.8500},
    {"id": "Pathahewaheta", "district": "Kandy", "province": "Central", "lat": 7.1167, "lon": 80.5167},
    {"id": "Ambanganga", "district": "Matale", "province": "Central", "lat": 7.6333, "lon": 80.5500},
    {"id": "Aranayake", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.2167, "lon": 80.1667},
    {"id": "Rattota", "district": "Matale", "province": "Central", "lat": 7.5333, "lon": 80.7500},
    {"id": "Walapane", "district": "Nuwara Eliya", "province": "Central", "lat": 7.0833, "lon": 80.8833},
    {"id": "Polpitigama", "district": "Kurunegala", "province": "North Western", "lat": 7.8833, "lon": 80.1833},
    {"id": "Mallawapitiya", "district": "Kurunegala", "province": "North Western", "lat": 7.3833, "lon": 80.4333},
    {"id": "Welimada", "district": "Badulla", "province": "Uva", "lat": 6.9000, "lon": 80.9167},
    {"id": "Ratnapura", "district": "Ratnapura", "province": "Sabaragamuwa", "lat": 6.6797, "lon": 80.3992},
    {"id": "Bulathkohipitiya", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.2833, "lon": 80.2167},
    {"id": "Yatinuwara", "district": "Kandy", "province": "Central", "lat": 7.2500, "lon": 80.6833},
    {"id": "Matale", "district": "Matale", "province": "Central", "lat": 7.4675, "lon": 80.6235},
    {"id": "Kothmale West", "district": "Nuwara Eliya", "province": "Central", "lat": 7.1000, "lon": 80.6000},
    {"id": "Alawwa", "district": "Kurunegala", "province": "North Western", "lat": 7.2833, "lon": 80.2500},
    {"id": "Badulla", "district": "Badulla", "province": "Uva", "lat": 6.9895, "lon": 81.0557},
    {"id": "Bibile", "district": "Monaragala", "province": "Uva", "lat": 7.1667, "lon": 81.2333},
    {"id": "Kuruvita", "district": "Ratnapura", "province": "Sabaragamuwa", "lat": 6.7500, "lon": 80.3167},
    {"id": "Kolonna", "district": "Ratnapura", "province": "Sabaragamuwa", "lat": 6.4333, "lon": 80.4667},
    {"id": "Udunuwara", "district": "Kandy", "province": "Central", "lat": 7.2167, "lon": 80.5833},
    {"id": "Dompe", "district": "Gampaha", "province": "Western", "lat": 7.0167, "lon": 80.0833},
    {"id": "Akurana", "district": "Kandy", "province": "Central", "lat": 7.3500, "lon": 80.6167},
    {"id": "Harispattuwa", "district": "Kandy", "province": "Central", "lat": 7.2833, "lon": 80.5667},
    {"id": "Pasbagekorale", "district": "Kandy", "province": "Central", "lat": 7.1333, "lon": 80.4167},
    {"id": "Dambulla", "district": "Matale", "province": "Central", "lat": 7.8731, "lon": 80.6517},
    {"id": "Pallepola", "district": "Matale", "province": "Central", "lat": 7.6333, "lon": 80.5833},
    {"id": "Norwood", "district": "Nuwara Eliya", "province": "Central", "lat": 6.8333, "lon": 80.6167},
    {"id": "Yatiyantota", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.0833, "lon": 80.3167},
    {"id": "Rideemaliyadda", "district": "Badulla", "province": "Uva", "lat": 6.9833, "lon": 81.0833},
    {"id": "Ibbagamuwa", "district": "Kurunegala", "province": "North Western", "lat": 7.7000, "lon": 80.3000},
    {"id": "Nuwara Eliya", "district": "Nuwara Eliya", "province": "Central", "lat": 6.9497, "lon": 80.7891},
    {"id": "Mawathagama", "district": "Kurunegala", "province": "North Western", "lat": 7.5333, "lon": 80.4500},
    {"id": "Ganga Ihala Korale", "district": "Kandy", "province": "Central", "lat": 7.3167, "lon": 80.7500},
    {"id": "Ukuwela", "district": "Matale", "province": "Central", "lat": 7.5167, "lon": 80.6167},
    {"id": "Nildandahinna", "district": "Nuwara Eliya", "province": "Central", "lat": 7.0833, "lon": 80.8833},
    {"id": "Mawanella", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.2500, "lon": 80.4500},
    {"id": "Warakapola", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.2500, "lon": 80.2167},
    {"id": "Poojapitiya", "district": "Kandy", "province": "Central", "lat": 7.4167, "lon": 80.7000},
    {"id": "Naula", "district": "Matale", "province": "Central", "lat": 7.7667, "lon": 80.7500},
    {"id": "Wilgamuwa", "district": "Matale", "province": "Central", "lat": 7.8167, "lon": 80.7500},
    {"id": "Hatharaliyadda", "district": "Kandy", "province": "Central", "lat": 7.1833, "lon": 80.7000},
    {"id": "Yatawatta", "district": "Matale", "province": "Central", "lat": 7.5833, "lon": 80.7833},
    {"id": "Pathadumbara", "district": "Kandy", "province": "Central", "lat": 7.2167, "lon": 80.7500},
    {"id": "Panvila", "district": "Kandy", "province": "Central", "lat": 7.2333, "lon": 80.6833},
    {"id": "Polgahawela", "district": "Kurunegala", "province": "North Western", "lat": 7.3333, "lon": 80.3000},
    {"id": "Rambukkana", "district": "Kegalle", "province": "Sabaragamuwa", "lat": 7.3333, "lon": 80.4167},
    {"id": "Udapalatha", "district": "Kandy", "province": "Central", "lat": 7.1833, "lon": 80.5667},
    {"id": "Vadamaradchchi East", "district": "Jaffna", "province": "Northern", "lat": 9.8333, "lon": 80.2500},
    {"id": "Galenbidunuwewa", "district": "Anuradhapura", "province": "North Central", "lat": 8.4500, "lon": 80.7000},
    {"id": "Thamankaduwa", "district": "Polonnaruwa", "province": "North Central", "lat": 7.9000, "lon": 81.0167},
    {"id": "Nanaddan", "district": "Mannar", "province": "Northern", "lat": 8.6667, "lon": 80.0000},
    {"id": "Oddusuddan", "district": "Mullaitivu", "province": "Northern", "lat": 9.1667, "lon": 80.7000},
    {"id": "Nuwaragam Palatha Central", "district": "Anuradhapura", "province": "North Central", "lat": 8.3333, "lon": 80.3667},
    {"id": "Muthur", "district": "Trincomalee", "province": "Eastern", "lat": 8.4567, "lon": 81.2267},
    {"id": "Kebithigollewa", "district": "Anuradhapura", "province": "North Central", "lat": 8.2833, "lon": 80.7667},
    {"id": "Thenmaradchi (Chavakachcheri)", "district": "Jaffna", "province": "Northern", "lat": 9.8000, "lon": 80.1000},
    {"id": "Nochchiyagama", "district": "Anuradhapura", "province": "North Central", "lat": 8.0500, "lon": 80.2500},
    {"id": "Higurakgoda", "district": "Polonnaruwa", "province": "North Central", "lat": 8.0500, "lon": 80.9667},
    {"id": "Galgamuwa", "district": "Kurunegala", "province": "North Western", "lat": 8.0667, "lon": 80.2667},
    {"id": "Mundel", "district": "Puttalam", "province": "North Western", "lat": 8.0667, "lon": 79.8500},
    {"id": "Mannar Town", "district": "Mannar", "province": "Northern", "lat": 8.9760, "lon": 79.9047},
    {"id": "Padaviya", "district": "Anuradhapura", "province": "North Central", "lat": 8.8500, "lon": 80.7000},
    {"id": "Vengalacheddikulam", "district": "Vavuniya", "province": "Northern", "lat": 8.8500, "lon": 80.4000},
    {"id": "Vavuniya North", "district": "Vavuniya", "province": "Northern", "lat": 8.8333, "lon": 80.5000},
    {"id": "Pachchilaipalli", "district": "Kilinochchi", "province": "Northern", "lat": 9.7833, "lon": 80.2000},
    {"id": "Kinniya", "district": "Trincomalee", "province": "Eastern", "lat": 8.5167, "lon": 81.2667},
    {"id": "Thirappane", "district": "Anuradhapura", "province": "North Central", "lat": 8.2167, "lon": 80.5167},
    {"id": "Thalawa", "district": "Anuradhapura", "province": "North Central", "lat": 8.2167, "lon": 80.5667},
    {"id": "Dimbulagala", "district": "Polonnaruwa", "province": "North Central", "lat": 7.9167, "lon": 81.2167},
    {"id": "Kandavalai", "district": "Kilinochchi", "province": "Northern", "lat": 9.4667, "lon": 80.3833},
    {"id": "Maritimepattu", "district": "Mullaitivu", "province": "Northern", "lat": 9.3833, "lon": 80.8167},
    {"id": "Welikanda", "district": "Polonnaruwa", "province": "North Central", "lat": 7.9500, "lon": 81.2500},
    {"id": "Medirigiriya", "district": "Polonnaruwa", "province": "North Central", "lat": 8.0667, "lon": 81.1667},
    {"id": "Horowpathana", "district": "Anuradhapura", "province": "North Central", "lat": 9.0000, "lon": 80.7333},
    {"id": "Poonakary", "district": "Kilinochchi", "province": "Northern", "lat": 9.3000, "lon": 80.2500},
    {"id": "Kantale", "district": "Trincomalee", "province": "Eastern", "lat": 8.4000, "lon": 81.0000},
    {"id": "Kuchchaweli", "district": "Trincomalee", "province": "Eastern", "lat": 8.7667, "lon": 81.0833},
    {"id": "Dehiattakandiya", "district": "Ampara", "province": "Eastern", "lat": 7.3833, "lon": 81.3333},
    {"id": "Koralai Pattu South", "district": "Batticaloa", "province": "Eastern", "lat": 7.5833, "lon": 81.7833},
    {"id": "Vavuniya", "district": "Vavuniya", "province": "Northern", "lat": 8.7514, "lon": 80.4971},
    {"id": "Koralai Pattu North", "district": "Batticaloa", "province": "Eastern", "lat": 7.7333, "lon": 81.7167},
    {"id": "Manthai West", "district": "Mannar", "province": "Northern", "lat": 8.8833, "lon": 79.9500},
    {"id": "Karachchi", "district": "Kilinochchi", "province": "Northern", "lat": 9.4500, "lon": 80.3500},
    {"id": "Mahiyanganaya", "district": "Badulla", "province": "Uva", "lat": 7.3297, "lon": 81.0000},
    {"id": "Kahatagasdigiliya", "district": "Anuradhapura", "province": "North Central", "lat": 8.5833, "lon": 80.7667},
    {"id": "Medawachchiya", "district": "Anuradhapura", "province": "North Central", "lat": 8.5333, "lon": 80.4833},
    {"id": "Kekirawa", "district": "Anuradhapura", "province": "North Central", "lat": 8.0500, "lon": 80.6167},
    {"id": "Rambewa", "district": "Anuradhapura", "province": "North Central", "lat": 8.2667, "lon": 80.3333},
    {"id": "Eravur Pattu", "district": "Batticaloa", "province": "Eastern", "lat": 7.8000, "lon": 81.6333},
    {"id": "Ambalantota", "district": "Hambantota", "province": "Southern", "lat": 6.10, "lon": 81.00},
    {"id": "Ehetuwewa", "district": "Kurunegala", "province": "North Western", "lat": 7.90, "lon": 80.20},
    {"id": "Giribawa", "district": "Kurunegala", "province": "North Western", "lat": 8.10, "lon": 80.10},
    {"id": "Gomarankadawala", "district": "Trincomalee", "province": "Eastern", "lat": 8.60, "lon": 81.00},
    {"id": "Karuwalagaswewa", "district": "Puttalam", "province": "North Western", "lat": 8.00, "lon": 79.90},
    {"id": "Lankapura", "district": "Polonnaruwa", "province": "North Central", "lat": 7.90, "lon": 81.00},
    {"id": "Mahawilachchiya", "district": "Anuradhapura", "province": "North Central", "lat": 8.40, "lon": 80.10},
    {"id": "Mihinthale", "district": "Anuradhapura", "province": "North Central", "lat": 8.35, "lon": 80.50},
    {"id": "Morawewa", "district": "Trincomalee", "province": "Eastern", "lat": 8.60, "lon": 80.90},
    {"id": "Musali", "district": "Mannar", "province": "Northern", "lat": 8.80, "lon": 79.90},
    {"id": "Palagala", "district": "Anuradhapura", "province": "North Central", "lat": 8.00, "lon": 80.50},
    {"id": "Sammanthurai", "district": "Ampara", "province": "Eastern", "lat": 7.30, "lon": 81.80},
    {"id": "Seruvila", "district": "Trincomalee", "province": "Eastern", "lat": 8.40, "lon": 81.20},
    {"id": "Thanamalwila", "district": "Monaragala", "province": "Uva", "lat": 6.40, "lon": 81.10},
    {"id": "Vavuniya South", "district": "Vavuniya", "province": "Northern", "lat": 8.70, "lon": 80.50},
    {"id": "Verugal", "district": "Trincomalee", "province": "Eastern", "lat": 8.20, "lon": 81.30},
    {"id": "Welioya", "district": "Mullaitivu", "province": "Northern", "lat": 8.80, "lon": 80.70}
]

def get_ds_by_district(district_name: str) -> list:
    return [ds for ds in DS_LOCATIONS if ds["district"].lower() == district_name.lower()]

def get_ds_by_province(province_name: str) -> list:
    return [ds for ds in DS_LOCATIONS if ds["province"].lower() == province_name.lower()]

def summary():
    from collections import Counter
    counts = Counter(ds["district"] for ds in DS_LOCATIONS)
    total = len(DS_LOCATIONS)
    print(f"\n{'District':<35} {'DS Count':>8}")
    print("-" * 45)
    for district, count in sorted(counts.items()):
        print(f"{district:<35} {count:>8}")
    print(f"\n{'TOTAL':<35} {total:>8}")

if __name__ == "__main__":
    summary()
